export const COLORS = {
    BACKGROUND_DARK: '#000814',
    PRIMARY_BLUE: '#003566',
    SECONDARY_BLUE: '#001d3d',
    ACCENT_BLUE: '#0D47A1',
    ACCENT_RED:'red',
    TEXT_WHITE: '#FFFFFF',
    TEXT_LIGHT_BLUE: '#B0BEC5'
  };